### ISSUE TITLE
Individual Repos

### ISSUE THREAD

**Issue by erichlf** [WolfgangMehner/vim-plugins#26]
It would be nice to have each of these plugins in their own repos.

Reasoning: I tend to clone a vim-plugin into .vim/bundle and let pathogen handle loading the plugin. In fact, I have my .vim file structure as a repo and each plugin is including as a submodule. This makes updating and backing up my configuration quite easy. 

Also, contributing to your plugins would be much easier, since I am sure there are people like me who may only be interested in one or two particle plugins.

**Comment by WolfgangMehner** [comment]
> It would be nice to have each of these plugins in their own repos.

Agreed. I was not in a hurry with this though, since https://github.com/vim-scripts has all your plug-ins from vim.org in separate repositories. Look at my starred repositories to find some of them: https://github.com/stars/WolfgangMehner

They are a little behind with the C plug-in, so we updated it: https://github.com/WolfgangMehner/c.vim 

> Also, contributing to your plugins would be much easier, since I am sure there are people like me who may only be interested in one or two particle plugins.

I'm unsure about that to be honest. We do all your development in "vim-plugins", the stand-alone repos I've created are all exact copies of the files in "vim-plugins". But people could still send me patches for the stand-alone repos, I would be able to patch them into the main one.

**Comment by WolfgangMehner** [comment]
Progress on this one:

AWK : missing
Bash: missing
C: see above
Git: https://github.com/WolfgangMehner/git-support
LaTeX: https://github.com/WolfgangMehner/latex-support
Lua: https://github.com/WolfgangMehner/lua-support
Perl: https://github.com/WolfgangMehner/perl-support
VimL: https://github.com/WolfgangMehner/vim-support

**Comment by WolfgangMehner** [comment]
Done for all plug-ins.
